baseurl = "https://ciaranshu.github.io"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
title = "Underflow"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling

  style = "sea"
  description = "Personal Blog of Chang Shu"
  copyright = "&copy; 2018 Chang Shu (Ciaran) | All Copyright Reserved | Currently Based in Edinburgh, United Kingdom"
  sidebarAbout = [
    "Tech: Bioinformatics/ Unsupervised Learning/ Natural Language Understanding",
    "Interests: Guitar/ Photography/ Traveling/ Reading/ Football/ Tennis",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "cscshu@outlook.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Photography"
  url = "photo/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Contact"
  url = "contact/"

  [params.social]
  github        = "https://github.com/Ciaranshu"
  facebook      = "https://www.facebook.com/ciaranshu"
  email         = "cscshu@outlook.com"
  linkedin      = "https://www.linkedin.com/in/ciaran-shu/"
  instagram     = "https://www.instagram.com/ciaranshu/"
